### ISSUE TITLE
Plugin fails when subsonic api is in a subfolder on the server.

### ISSUE THREAD

**Issue by pyongyang666** [basilfx/plugin.audio.subsonic#1]
It's probably going to be clearer if I provide a practical example for this.

I have ampache running on my server at https://myserver.url/ampache/. This means that the hook for the subsonic api is located /ampache/rest/. The plugin will only try to access the api at /rest/, meaning lots of fun errors. Messing with the server address settings in the configuration is unsuprisingly useless. Editing serverPath='/rest' to serverPath='/ampache/rest' on line 95 of /lib/libsonic/connection.py resolves the issue.

**Comment by basilfx** [comment]
Can you try to modify [this line](https://github.com/basilfx/plugin.audio.subsonic/blob/master/lib/libsonic_extra/__init__.py#L62) to the following:

```
host = "%s://%s%s" % (scheme, parts.hostname, parts.path)
```

I don't have a working setup here to test it myself, but this should add the /ampache/ part to the URL.

**Comment by pyongyang666** [comment]
Okay reverted my change, did the above. Failure. Reason should be obvious given what I'm seeing in my nginx log:

"POST /ampache/:443/rest/getArtists.view HTTP/1.1"
