### ISSUE TITLE
not working anymore ?

### ISSUE THREAD

**Issue by gordielachance** [basilfx/plugin.audio.subsonic#3]
Hi !

I did try your plugin on Kodi Jarvis but it's not working...
Is this still in developement ?

Thanks

**Comment by basilfx** [comment]
Hi,

I don't use it myself anymore, so I don't know if it works. Feel free to submit a patch.

Kind regards,
Bas

**Comment by gordielachance** [comment]
Hi,

So sad :/

Unfortunately I have no skills in python...



2016-05-11 15:03 GMT+02:00 Bas Stottelaar <notifications@github.com>:

**Comment by gordielachance** [comment]
it works on kodi Krypton Alpha for Mac OS X, but not for kodi krypton with LibreELEC.

> **AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'**
